using System;
using JsonSerializer = System.Text.Json.JsonSerializer;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BH.DIS.MessageStore;
using BH.DIS.WebApp.ManagementApi;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;
using BH.DIS.WebApp.Hubs;
using System.IO;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Text;
using Microsoft.Extensions.Logging;

// Make autogenerated controller anonymous access
namespace BH.DIS.WebApp.ManagementApi
{
    [AllowAnonymous]
    public partial class StorageHookApiController : Controller { }
}

namespace BH.DIS.WebApp.Controllers
{
    public class StorageHookImplementation : IStorageHookApiController
    {
        private readonly HttpContext Context;

        private readonly IHubContext<GridEventsHub> _hubContext;

        private readonly IMessageStoreClient _messageStoreClient;
        private readonly ILogger<StorageHookImplementation> logger;
        private readonly ICosmosDbClient _cosmosClient;

        public StorageHookImplementation(IHttpContextAccessor contextAccessor, IHubContext<GridEventsHub> gridEventsHubContext, IMessageStoreClient messageStoreClient, ILogger<StorageHookImplementation> logger, ICosmosDbClient cosmosClient)
        {
            this._hubContext = gridEventsHubContext;
            this._messageStoreClient = messageStoreClient;
            this.Context = contextAccessor.HttpContext;
            this.logger = logger;
            this._cosmosClient = cosmosClient;
        }

        public async Task<IActionResult> StoragehookReceiveCosmosAsync(string endpointId)
        {
            if (!string.IsNullOrEmpty(endpointId))
            {
                var state = await _cosmosClient.DownloadEndpointStateCount(endpointId);
                var endpointStatus = Mapper.EndpointStatusCountFromEndpointStateCount(state);
                await _hubContext.Clients.All.SendAsync(Constants.EventSignalNames.EndpointUpdate, endpointStatus);
                return new OkResult();
            }

            return new BadRequestResult();
        }

        public async Task<IActionResult> PostApiStoragehookHeartbeatEndpointIdAsync(string endpointId)
        {
            if (!string.IsNullOrEmpty(endpointId))
            {
                var metadata = await _cosmosClient.GetEndpointMetadata(endpointId);
                var metadataShort = Mapper.MetadataShortFromMetadata(metadata);
                await _hubContext.Clients.All.SendAsync(Constants.EventSignalNames.HeartbeatUpdate, metadataShort);
                return new OkResult();
            }

            return new BadRequestResult();
        }

        public Task<IActionResult> StoragehookOptionsAsync(string webHook_Request_Origin, string webHook_Request_Callback, string webHook_Request_Rate)
        {
            Context.Response.Headers.Add("Webhook-Allowed-Rate", "*");
            Context.Response.Headers.Add("Webhook-Allowed-Origin", webHook_Request_Origin);
            return Task.FromResult<IActionResult>(new OkResult());
        }


        public async Task<IActionResult> StoragehookReceiveAsync(AegEventType? aeg_event_type, IEnumerable<dynamic> body)
        {
            if (body == null)
            {
                return await Task.FromResult<IActionResult>(new BadRequestObjectResult("Empty body"));
            }

            // MUST use System.Text.Json to reserialize here -- object comes in as JsonElement
            var jsonContent = JsonSerializer.Serialize(body);

            // Check the event type.
            // Return the validation code if it's event_publisher_function
            // a subscription validation request. 
            if (aeg_event_type == AegEventType.SubscriptionValidation)
            {
                return await HandleValidation(jsonContent);
            }
            else if (aeg_event_type == AegEventType.Notification)
            {
                // Check to see if this is passed in using
                // the CloudEvents schema
                if (IsCloudEvent(jsonContent))
                {
                    return await HandleCloudEvent(jsonContent);
                }

                await HandleGridEvents(jsonContent);

                var endpointEvents = FilterEndpointStateEvents(jsonContent);
                return await HandleEndpointStateEvents(endpointEvents);
            }

            return new BadRequestResult();
        }

        private async Task<JsonResult> HandleValidation(string jsonContent)
        {
            var gridEvent =
                JsonConvert.DeserializeObject<List<GridEventOfStorageEventData>>(jsonContent)
                    .First();

            await this._hubContext.Clients.All.SendAsync(
                Constants.EventSignalNames.GridUpdate,
                gridEvent.Id,
                gridEvent.EventType,
                gridEvent.Subject,
                gridEvent.EventTime,
                jsonContent.ToString());

            // Retrieve the validation code and echo back.
            logger.LogInformation(jsonContent);
            if (gridEvent.Data.ContainsKey("validationCode"))
            {
                string validationCode = gridEvent.Data["validationCode"];
                return new JsonResult(new
                {
                    validationResponse = validationCode
                });
            }
            else
            {
                throw new ArgumentException(
                    $"Header was SubscriptionValidation, but no validationCode found in '{jsonContent}'");
            }

        }

        private async Task<IActionResult> HandleEndpointStateEvents(IEnumerable<GridEventOfStorageEventData> events)
        {
            foreach (var e in events)
            {
                // TODO: consider tracking Client count for hub and avoid downloading the state when nobody's listening
                var sub = e.Subject.Split("/containers/").LastOrDefault();
                var containerName = sub.Split("/").FirstOrDefault<string>();
                var name = containerName.Split("-").FirstOrDefault<string>();
                var state = await _cosmosClient.DownloadEndpointStateCount(name);
                var endpointStatus = Mapper.EndpointStatusCountFromEndpointStateCount(state);
                await this._hubContext.Clients.All.SendAsync(Constants.EventSignalNames.EndpointUpdate, endpointStatus);
            }

            return new OkResult();
        }

        private async Task<IActionResult> HandleGridEvents(string jsonContent)
        {
            var events = JArray.Parse(jsonContent);
            foreach (var e in events)
            {
                // Invoke a method on the clients for 
                // an event grid notiification.                        
                var details = JsonConvert.DeserializeObject<GridEventOfStorageEventData>(e.ToString());
                await this._hubContext.Clients.All.SendAsync(
                    Constants.EventSignalNames.GridUpdate,
                    details.Id,
                    details.EventType,
                    details.Subject,
                    details.EventTime,
                    e.ToString());
            }

            return new OkResult();
        }

        private async Task<IActionResult> HandleCloudEvent(string jsonContent)
        {
            var details = JsonConvert.DeserializeObject<CloudEvent>(jsonContent);
            var eventData = JObject.Parse(jsonContent);

            await this._hubContext.Clients.All.SendAsync(
                Constants.EventSignalNames.GridUpdate,
                details.Id,
                details.Type,
                details.Subject,
                details.Time,
                eventData.ToString()
            );

            return new OkResult();
        }

        private static bool IsCloudEvent(string jsonContent)
        {
            // Cloud events are sent one at a time, while Grid events
            // are sent in an array. As a result, the JObject.Parse will 
            // fail for Grid events. 
            try
            {
                // Attempt to read one JSON object. 
                var eventData = JObject.Parse(jsonContent);

                // Check for the spec version property.
                var version = eventData["specversion"].Value<string>();
                if (!string.IsNullOrEmpty(version)) return true;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            return false;
        }

        private IEnumerable<GridEventOfStorageEventData> FilterEndpointStateEvents(string jsonContent)
        {
            logger.LogInformation(jsonContent);
            var events = JsonConvert.DeserializeObject<List<GridEventOfStorageEventData>>(jsonContent);
            var filteredEvents = new List<GridEventOfStorageEventData>();
            foreach (var e in events)
            {
                logger.LogInformation($"{e}");
                if (e.Subject.Contains("-pending") || e.Subject.Contains("-deferred") || e.Subject.Contains("-failed"))
                {
                    filteredEvents.Add(e);
                }
            }
            return filteredEvents;
        }


    }
}
